import React from "react";

export const data = [
    {
        id: 1,
        problem: "What is the capital of France?",
        ans1: "Berlin",
        ans2: "Madrid",
        ans3: "Paris",
        ans4: "Lisbon",
        img: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Paris_Night.jpg",
        correct: 3,
        isticked: 0,
        timers: 10,
    },
    {
        id: 2,
        problem: "Which planet is known as the Red Planet?",
        ans1: "Earth",
        ans2: "Mars",
        ans3: "Jupiter",
        ans4: "Saturn",
        img: "https://upload.wikimedia.org/wikipedia/commons/0/02/OSIRIS_Mars_true_color.jpg",
        correct: 2,
        isticked: 0,
        timers: 10,
    },
    {
        id: 3,
        problem: "Who wrote 'To Kill a Mockingbird'?",
        ans1: "Harper Lee",
        ans2: "Mark Twain",
        ans3: "Ernest Hemingway",
        ans4: "F. Scott Fitzgerald",
        img: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Harper_Lee_Nov07.jpg",
        correct: 1,
        isticked: 0,
        timers: 10,
    },
    {
        id: 4,
        problem: "What is the largest ocean on Earth?",
        ans1: "Atlantic Ocean",
        ans2: "Indian Ocean",
        ans3: "Arctic Ocean",
        ans4: "Pacific Ocean",
        img: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Pacific_Ocean_-_en.svg",
        correct: 4,
        isticked: 0,
        timers: 10,
    },
    {
        id: 5,
        problem: "Who painted the Mona Lisa?",
        ans1: "Vincent van Gogh",
        ans2: "Pablo Picasso",
        ans3: "Leonardo da Vinci",
        ans4: "Claude Monet",
        img: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
        correct: 3,
        isticked: 0,
        timers: 10,
    },
    {
        id: 6,
        problem: "What is the smallest country in the world?",
        ans1: "Monaco",
        ans2: "Vatican City",
        ans3: "San Marino",
        ans4: "Liechtenstein",
        img: "",
        correct: 2,
        isticked: 0,
        timers: 10,
    },
];
